config/routes.rb
Rails.application.routes.draw do
  root "static_pages#landing_page"
  get "privacy_policy", to:"static_pages#privacy_policy"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing_page
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyGemsBootcamp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/landing_page.html.erb
<div class="container mt-5">
  <h3> Hello World!</h3>
  <%= link_to privacy_policy_path, class: "btn btn-lg btn-outline-warning" do %>
    <i class="fa-solid fa-building-shield"></i>
    Privacy Policy
  <% end %>
</div>

app/views/static_pages/privacy_policy.html.erb
<div class="container mt-5">
  <h3>Privacy Policy</h3>
  <%= link_to root_path, class: "btn btn-lg  btn-outline-success" do %>
    <i class="fas fa-home"></i>
    Home
  <% end %>
</div>